name: Test

permissions: 
  contents: read 
on: 
    push: 
        branches: [main]
    pull_request: 
        branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ruff_checking: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run ruff
        uses: ./.github/actions/python-env
        with:
          install: pip install ruff
          command: ruff check .

  test:
    needs: ruff_checking
    runs-on: ubuntu-24.04
    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
      postgres:
        image: postgres:16
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
    env:
      TEST_DATABASE_URL: postgresql://postgres:test@localhost:5432/test_db
      REDIS_TEST_URL: redis://localhost:6379
      ADMIN_API_KEY: ${{ secrets.ADMIN_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: run app
        uses: ./.github/actions/python-env
        with: 
          install: pip install -r requirements-dev.txt
          command: pytest --junit-xml=reports/pytest.xml
          cache: pip
        
      - name: failing tests
        uses: actions/upload-artifact@v4
        if: failure()
        with: 
          name: pytest-report
          path: reports/pytest.xml
          if-no-file-found: error
          overwrite: true

          
          

